name: User Story
description: Standard template for user stories (Exercises 2 to 8)
title: "[STORY]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this form to document your feature request.
  - type: textarea
    id: description
    attributes:
      label: "User Story Description"
      placeholder: "As a [user role], I want [action], so that [benefit]."
    validations:
      required: true
  - type: textarea
    id: criteria
    attributes:
      label: "Acceptance Criteria"
      placeholder: "1. Feature X is visible\n2. Action Y triggers Z..."
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "priority: high"
        - "priority: medium"
        - "priority: low"
    validations:
      required: true
  - type: input
    id: points
    attributes:
      label: "Estimation (Story Points)"
      placeholder: "1, 2, 3, 5, 8..."
  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes"
      placeholder: "Technical constraints, linked bugs, or reminders (e.g., default credentials)."
